version: '3'

services:
   app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/usr/src/app

   zookeeper:
     container_name: zookeeper
     image: 'bitnami/zookeeper:latest'
     tmpfs: "/datalog"
     ports:
       - '2181:2181'
     environment:
       - ALLOW_ANONYMOUS_LOGIN=yes

   kafka:
     container_name: kafka
     build:
       context: kafka
       dockerfile: Dockerfile
     # image: 'bitnami/kafka:latest'
     ports:
       - '9092:9092'
     expose:
       - "9092"
     environment:
       - KAFKA_BROKER_ID=1
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
       - ALLOW_PLAINTEXT_LISTENER=yes
     depends_on:
       - zookeeper
